### ISSUE TITLE
Board Support

### ISSUE THREAD

**Issue by hermannsblum** [ethz-asl/versavis#12]
Minor Bug:

Additionally to the VersaVIS Board Support, I still had to install Arduino SAMD Boards for the compilation to succeed. Probably this can be fixed, or corrected in the instructions.

**Comment by michaelriner** [comment]
Solved

New and fixed VersaVIS package for Arduino IDE now available:

- Dedicated VersaVIS Booloader
- Package installation installs now compiler too
- Package derived from newest Arduino SAMD distribution (1.8.6)
- Elimination of all unecessary overhead
