### ISSUE TITLE
board support

### ISSUE THREAD

**Issue by Yeah2333** [ethz-asl/versavis#27]
thanks for your work. I want to build this borad to test lidar and camera sync. I find gerber file in versavis_hw，i give this file to manufacturer. They told me i should provide the BOM file. How can i get bom file?

**Comment by floriantschopp** [comment]
Hi @Yeah2333 
We added an example bom in the [versavis_hw](https://github.com/ethz-asl/versavis_hw/blob/master/Bom_VersaVis_DigiKey.csv) repository.
Hope this helps.

**Comment by Yeah2333** [comment]
Hi @floriantschopp thanks for the bom file.i think this file will help.
