### ISSUE TITLE
Board Support

### ISSUE THREAD

**Issue by MasterY0416** [ethz-asl/versavis#29]
This is a great job. I also want to build the same board to test the synchronization of lidar and IMU. Could you export the coordinate file for the SMT placement machine from Altium Designer? Need to perform a "Gernerates pick and place files" setting in Altium Designer.This will help me immensely. Thank you!

**Comment by zhangyuan12121** [comment]
This is a great job. I also want to build the same board to test the synchronization of lidar and IMU. Could you export the coordinate file for the SMT placement machine from Altium Designer? Need to perform a "Gernerates pick and place files" setting in Altium Designer.This will help me immensely. Thank you!

**Comment by Alex-Beh** [comment]
@MasterY0416 Hi, I am looking for pick and place files also. Do you manage to find the file eventually? Besides, how is your experience with the versavis board?
