### ISSUE TITLE
about IMU

### ISSUE THREAD

**Issue by MasterY0416** [ethz-asl/versavis#35]
Hello,  @floriantschopp. Thank you for your open source work. I see that the PPT of VersaVIS shows that the trigger board can be compatible with Xsens. I will use Xsens and Basler to observe the synchronization effect of trigger board. May I ask you what suggestions are you can use Xsens on VersaVIS

**Comment by floriantschopp** [comment]
I have not integrated Xsens yet, this was in the presentation more as a potential sensor to integrate. But you could have a look at the integration for the [VectorNAV VN-100 ](https://github.com/ethz-asl/versavis/pull/7) for some inspiration :-)
