### ISSUE TITLE
Timing issue with nh.now() offset

### ISSUE THREAD

**Issue by Hommus** [ethz-asl/versavis#37]
Hi @floriantschopp, I'm not sure if this project is still maintained but I would love some help debugging a timing issue.

I have multiple cameras and an IMU connected with versavis. All data streams have been verified and triggering is working perfectly. However, when the timestamps are retrieved with `nh.now()`, they get worse with time. For example, when Versavis starts running, the timestamp offset between the MCU and our host computer is 0. Afterwards, roughly every 30-40 seconds (measured with a stopwatch), the offset increments by 4294 seconds (measured with `rostopic echo topic --offset`). 

Any idea of what is going on?

**Comment by Hommus** [comment]
After a bit of digging, it seems this issue is related to your implementation of `time_micros()` in `ArduinoHardware.h`.

**Comment by Hommus** [comment]
@floriantschopp What was the intention behind the custom `time_micros()` function instead of just using the default `micros()` function?

**Comment by floriantschopp** [comment]
Hi @Hommus 
It is partially maintained / kept alive as long as people use it :-) 
IIRC, the problem with the original `micros()` is that it was overflowing after a few hours of use. The issue you are describing most likely relates to the on-board syncing EKF or how the data is received/sent. For debugging this, you could try the branch https://github.com/ethz-asl/versavis/tree/ekf_evaluation and send a trace of the topics published there, i.e. `/versavis/ekf/offset`

**Comment by Hommus** [comment]
Thanks for the response @floriantschopp!
Going through your edits of `node_handle.h`, it looks like you've deleted a point of synchronisation, can you remember why?

![image](https://user-images.githubusercontent.com/7821954/220211100-bdd80274-73a0-4ede-9c7b-60099d4b0efe.png)

**Comment by Hommus** [comment]
@floriantschopp 
Another question to add:

Our cameras use the NVIDIA Argus driver which stores 2 frames in an internal buffer before making the images accessible to the user space. Therefore we have to trigger the camera 3 times before the 1st image arrives. This has the effect that each trigger is associated with the wrong image. 

We have accounted for this in the `associateTimeStampsAndCleanUp` function by adding 2 to the `offset_`, but is this the only logic that might need updating? 

We're still getting a ~65ms time offset between the camera and imu, so we're trying to track down possible causes.

**Comment by floriantschopp** [comment]
@Hommus 
I can't remember the reason for this specific change, I have to dive back into the code to remember :-) Maybe I have some time on the weekend.
What a weird way to handle images! What framerate are you using the cameras with? 65ms is rather high, but if you do some agressive IMU filtering it can be reasonable.

**Comment by Hommus** [comment]
@floriantschopp It is a weird way indeed. The framerate is 30FPS but we can run the cameras at 60FPS as well.
Thanks for your help!
